# Generated by Django 6.0.3 on 2026-04-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedEdu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='fine',
            field=models.IntegerField(default=0),
        ),
    ]
