# Generated by Django 6.0.3 on 2026-03-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedEdu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.AddField(
            model_name='user',
            name='mededu_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='00000000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Medical & Dental Student'), ('intern', 'Intern Doctor'), ('faculty', 'Faculty / Department Head'), ('doctor', 'Doctor'), ('ward', 'Hospital Register'), ('library', 'Library Staff'), ('admin', 'Academic Administration')], max_length=20),
        ),
    ]
