# Generated by Django 6.0.3 on 2026-05-14 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedEdu', '0002_alter_attendance_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('news', 'Medical News'), ('career', 'Career Opportunity'), ('research', 'Research'), ('seminar', 'Seminar'), ('scholarship', 'Scholarship')], max_length=30)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
