# Generated by Django 6.0.3 on 2026-04-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedEdu', '0002_issue_fine'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('card', 'Card'), ('term', 'Term')], max_length=10)),
                ('course', models.CharField(choices=[('MBBS', 'MBBS'), ('BDS', 'BDS')], max_length=10)),
                ('phase', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
