# Generated by Django 6.0.3 on 2026-03-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedEdu', '0002_remove_user_department_user_mededu_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
