# Generated by Django 6.0.3 on 2026-03-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedEdu', '0003_user_is_verified_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('medical_student', 'Medical Student'), ('dental_student', 'Dental Student'), ('intern', 'Intern Doctor'), ('faculty', 'Faculty'), ('doctor', 'Doctor'), ('ward', 'Ward Authority'), ('library', 'Library Staff'), ('admin', 'Admin')], max_length=20),
        ),
    ]
