# Generated by Django 6.0.3 on 2026-05-15 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedEdu', '0005_medicalupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wardswaprequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requested_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wardswaprequest',
            name='swap_with',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_with_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
