# Generated by Django 6.0.3 on 2026-05-01 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedEdu', '0005_remove_payment_note_payment_bank_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('card', 'Card'), ('term', 'Term'), ('prof', 'Prof')], max_length=10)),
                ('is_eligible', models.BooleanField(default=False)),
                ('attendance_ok', models.BooleanField(default=False)),
                ('item_clear', models.BooleanField(default=False)),
                ('card_clear', models.BooleanField(default=False)),
                ('term_clear', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_status', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('class', 'Class'), ('ward', 'Ward'), ('duty', 'Duty')], max_length=10)),
                ('total_classes', models.IntegerField(default=0)),
                ('attended_classes', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
