# Generated by Django 6.0.3 on 2026-04-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedEdu', '0005_subject_topic_result_examschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='course_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='phase',
            field=models.IntegerField(),
        ),
    ]
