# Generated by Django 6.0.3 on 2026-05-01 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedEdu', '0006_academicstatus_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='attended_classes',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='total_classes',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='type',
        ),
        migrations.AddField(
            model_name='attendance',
            name='class_attendance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='duty_attendance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='ward_attendance',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Eligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('card', 'Card'), ('term', 'Term'), ('prof', 'Prof')], max_length=10)),
                ('eligible', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AcademicStatus',
        ),
    ]
