# Generated by Django 6.0.3 on 2026-04-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedEdu', '0006_alter_subject_course_type_alter_subject_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
