# Generated by Django 6.0.3 on 2026-05-01 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedEdu', '0007_remove_attendance_attended_classes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eligibility',
            name='user',
        ),
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.IntegerField(default=0)),
                ('item_pass', models.BooleanField(default=False)),
                ('card_pass', models.BooleanField(default=False)),
                ('term_pass', models.BooleanField(default=False)),
                ('payment_clear', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Eligibility',
        ),
    ]
